# Cloud Watch event rule used to 
# automatically run the pipeline when code is committed
CodeRepositoryEvent:
  Type: AWS::Events::Rule
  Properties:
    Description: Rule for Amazon CloudWatch Events to detect changes to the source repository and trigger pipeline execution
    EventPattern:
      detail:
        event:
        - referenceCreated
        - referenceUpdated
        referenceName:
        - !Ref BranchName
        referenceType:
        - branch
      detail-type:
      - CodeCommit Repository State Change
      resources:
      - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${RepositoryName}'
      source:
      - aws.codecommit
    Name: !Sub "${PipelineName}-SourceEvent"
    State: ENABLED
    Targets:
    - Arn: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${PipelineName}'
      Id: ProjectPipelineTarget
      RoleArn: !GetAtt 'CodeRepositoryEventRole.Arn'
